server:
  port: 8082

spring:
  application:
    name: identity-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    enabled: true
  instance:
    prefer-ip-address: true
    hostname: localhost
    instance-id: ${spring.application.name}:${server.port}

jwt:
  signerKey: R9/kuvfe0dMDFtivCBkQFFuUMa2JbhBF6Lm+9cO2DsPQ6gNdqMBdWnWa43S6a9sHz/3gFeIRdshdjQx2MSiWRA==
